# Generated by Django 5.0.1 on 2025-12-01 04:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0003_product_reserved_stock'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('status', models.CharField(choices=[('RESERVED', 'Reservado'), ('FULFILLED', 'Cumplido'), ('CANCELED', 'Cancelado')], default='RESERVED', max_length=10, verbose_name='Estado')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='customers.customer', verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
