# Generated by Django 5.0.1 on 2025-12-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Clave')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Plantilla WhatsApp',
                'verbose_name_plural': 'Plantillas WhatsApp',
                'ordering': ['key'],
            },
        ),
    ]
