# Generated by Django 5.0.1 on 2025-12-02 00:53

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_admin_user(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    username = 'admin'
    email = 'admin@agrotecnica.com'
    password = 'admin123'
    
    if not User.objects.filter(username=username).exists():
        User.objects.create(
            username=username,
            email=email,
            password=make_password(password),
            first_name='Administrador',
            last_name='Sistema',
            role='ADMIN',
            is_staff=True,
            is_superuser=True,
            is_active=True
        )
        print(f'\nUsuario admin creado exitosamente en la migración')
    else:
        # Actualizar usuario existente
        user = User.objects.get(username=username)
        user.password = make_password(password)
        user.email = email
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.role = 'ADMIN'
        user.save()
        print(f'\nUsuario admin actualizado exitosamente en la migración')

def reverse_create_admin_user(apps, schema_editor):
    # No eliminamos el usuario en reverse para evitar pérdida de datos accidental
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_whatsapptemplate'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_create_admin_user),
    ]
