# Generated by Django 5.0.1 on 2025-12-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Borrador'),
        ),
    ]
